/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.*;
import Controller.ctlProducto;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PEDRO FONSECA
 */
public class FrmVentas extends javax.swing.JFrame {

    ctlProducto ctlProducto;
    LinkedList<Producto> productoObjetoLista = new LinkedList<>();
    LinkedList<Envio> EnvioObjetoLista = new LinkedList<>();
    LinkedList<Cliente> clienteObjetoLista = new LinkedList<>();

    /**
     * Creates new form FrmVentas
     */
    public FrmVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listEnvio = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtidEnvio = new javax.swing.JTextField();
        txtfechaEnvio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdireccionFacturacion = new javax.swing.JTextField();
        btncrearEnvio = new javax.swing.JButton();
        btnbuscarEnvio = new javax.swing.JButton();
        btneditarEnvio = new javax.swing.JButton();
        btneliminarEnvio = new javax.swing.JButton();
        cbcompania = new javax.swing.JComboBox<>();
        cbFinalizado = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtnombreProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprecioProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbproveedor = new javax.swing.JComboBox<>();
        txtidProducto = new javax.swing.JTextField();
        btcrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidCliente = new javax.swing.JTextField();
        txtdireccionCliente = new javax.swing.JTextField();
        txttelefonoCliente = new javax.swing.JTextField();
        txtemailCliente = new javax.swing.JTextField();
        btncrearCliente = new javax.swing.JButton();
        btnbuscarCliente = new javax.swing.JButton();
        btneditarCliente = new javax.swing.JButton();
        btneliminarCliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Prouducto 1", "Prouducto 2", "Prouducto 3", "Prouducto 4", "Prouducto 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        listEnvio.addTab("Lista de producto ", jPanel1);

        jLabel12.setText("ID de Envio");

        jLabel13.setText("Fecha de Envio");

        jLabel15.setText("Direccion Faturacion");

        jLabel16.setText("Compañia de Envio");

        btncrearEnvio.setText("Crear");
        btncrearEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearEnvioActionPerformed(evt);
            }
        });

        btnbuscarEnvio.setText("Buscar");
        btnbuscarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarEnvioActionPerformed(evt);
            }
        });

        btneditarEnvio.setText("Editar");
        btneditarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarEnvioActionPerformed(evt);
            }
        });

        btneliminarEnvio.setText("Eliminar");
        btneliminarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarEnvioActionPerformed(evt);
            }
        });

        cbcompania.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servientrega", "Interrapidisimo", "Envia", "Deprisa" }));

        cbFinalizado.setText("Finalizado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbFinalizado))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(txtfechaEnvio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 56, Short.MAX_VALUE)
                                .addComponent(btncrearEnvio)
                                .addGap(48, 48, 48)
                                .addComponent(btnbuscarEnvio)
                                .addGap(52, 52, 52)
                                .addComponent(btneditarEnvio)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdireccionFacturacion)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btneliminarEnvio))
                            .addComponent(cbcompania, 0, 147, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtidEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtdireccionFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtfechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbcompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(cbFinalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminarEnvio)
                    .addComponent(btneditarEnvio)
                    .addComponent(btnbuscarEnvio)
                    .addComponent(btncrearEnvio))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        listEnvio.addTab("Envio", jPanel3);

        jLabel2.setText("ID de Producto");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Denominacion");

        txtnombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreProductoActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio");

        jLabel11.setText("Proveedor");

        cbproveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LG", "Apple", "Xiaomi", "Sony" }));

        txtidProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidProductoActionPerformed(evt);
            }
        });

        btcrear.setText("Crear");
        btcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcrearActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtprecioProducto)
                            .addComponent(txtidProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btcrear)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombreProducto)
                            .addComponent(cbproveedor, 0, 130, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addContainerGap(152, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(cbproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcrear)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnBuscar))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        listEnvio.addTab("Producto", jPanel2);

        jLabel3.setText("ID Cliente ");

        jLabel4.setText("Direccion");

        jLabel5.setText("Telefono");

        jLabel8.setText("Email");

        btncrearCliente.setText("Crear");
        btncrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearClienteActionPerformed(evt);
            }
        });

        btnbuscarCliente.setText("Buscar");
        btnbuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarClienteActionPerformed(evt);
            }
        });

        btneditarCliente.setText("Editar");
        btneditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarClienteActionPerformed(evt);
            }
        });

        btneliminarCliente.setText("Eliminar");
        btneliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttelefonoCliente))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtemailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtdireccionCliente)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btncrearCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneditarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminarCliente)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txttelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrearCliente)
                    .addComponent(btnbuscarCliente)
                    .addComponent(btneditarCliente)
                    .addComponent(btneliminarCliente))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        listEnvio.addTab("Clientes", jPanel6);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        listEnvio.addTab("Lista Clientes", jPanel5);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        listEnvio.addTab("Lista Envio", jPanel7);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Administrador de ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listEnvio)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(listEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idProducto = txtidProducto.getText();
        boolean found = false;
        for (Producto producto : productoObjetoLista) {
            if (producto.getIdProducto().equals(idProducto)) {
                txtnombreProducto.setText(producto.getDenominacion());
                txtidProducto.setText(producto.getIdProducto());
                txtprecioProducto.setText(producto.getPrecio());
                cbproveedor.setSelectedItem(producto.getProveedor());

                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrearActionPerformed
        String idProducto = txtidProducto.getText();
        String precio = txtprecioProducto.getText();
        String proveedor = cbproveedor.getSelectedItem().toString();
        String denominacion = txtnombreProducto.getText();

        if (idProducto.equals("") || denominacion.equals("") || precio.equals("")) {
            JOptionPane.showMessageDialog(this, "debes llenar todos los campos");
        } else { 
            Producto productoUno = new Producto(idProducto, denominacion, proveedor, precio);
           ctlProducto.CreateProducto(productoUno);
            //productoObjetoLista.add(productoUno);
            this.listProducto();
            JOptionPane.showMessageDialog(this, "Registro Exitoso");
        }
    }

    private void listProducto() {

        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (Producto producto : productoObjetoLista) {
            String data = producto.getIdProducto() + " - " + producto.getPrecio() + " - " + producto.getProveedor() + " - " + producto.getDenominacion();
            model.add(index, data);
            index++;
        }

        jList.setModel(model);
    }//GEN-LAST:event_btcrearActionPerformed

    private void txtnombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreProductoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idProducto = txtidProducto.getText();
        boolean found = false;
        for (Producto producto : productoObjetoLista) {
            if (producto.getIdProducto().equals(idProducto)) {
                this.productoObjetoLista.remove(producto);
                this.limpiarCamposProducto();
                this.listProducto();
                JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idProducto = txtidProducto.getText();
        boolean found = false;
        for (Producto producto : productoObjetoLista) {
            if (producto.getIdProducto().equals(idProducto)) {
                String denominacion = txtnombreProducto.getText();
                String idPro = txtidProducto.getText();
                String precio = txtprecioProducto.getText();
                String proveedor = cbproveedor.getSelectedItem().toString();
                producto.setDenominacion(denominacion);
                producto.setIdProducto(idProducto);
                producto.setPrecio(precio);
                producto.setProveedor(proveedor);
                this.limpiarCamposProducto();
                this.listProducto();
                JOptionPane.showMessageDialog(this, "Editado Correctamente");
                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btncrearEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearEnvioActionPerformed
        String envios = txtidEnvio.getText();
        String direccion = txtdireccionFacturacion.getText();
        boolean finalizado = cbFinalizado.isSelected();
        String fechaEnvio = txtfechaEnvio.getText();
        String compania = cbcompania.getSelectedItem().toString();

        if (envios.equals("") || direccion.equals("") || fechaEnvio.equals("")) {
            JOptionPane.showMessageDialog(this, "debes llenar todos los campos");
        } else {
            Envio envioUno = new Envio(envios, direccion, finalizado, fechaEnvio, compania);
            EnvioObjetoLista.add(envioUno);
            this.listEnvio();
            JOptionPane.showMessageDialog(this, "Registro Exitoso");
        }
    }

    private void listEnvio() {

        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (Envio envio : EnvioObjetoLista) {
            String data = envio.getIdEnvio() + " - " + envio.getDireccionFacturacion() + " - " + envio.getFechaEnvio() + " - " + envio.getCompania();
            model.add(index, data);
            index++;
        }

        jList2.setModel(model);
    }//GEN-LAST:event_btncrearEnvioActionPerformed

    private void btnbuscarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarEnvioActionPerformed
        String idEnvio = txtidEnvio.getText();
        boolean found = false;
        for (Envio envio : EnvioObjetoLista) {
            if (envio.getIdEnvio().equals(idEnvio)) {
                txtfechaEnvio.setText(envio.getFechaEnvio());
                txtdireccionFacturacion.setText(envio.getDireccionFacturacion());
                cbcompania.setSelectedItem(envio.getCompania());
                cbFinalizado.setSelected(envio.isFinalizado());

                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btnbuscarEnvioActionPerformed

    private void btneditarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarEnvioActionPerformed
        String idenvio = txtidEnvio.getText();
        boolean found = false;
        for (Envio envio : EnvioObjetoLista) {
            if (envio.getIdEnvio().equals(idenvio)) {
                String idEnvio = txtidEnvio.getText();
                String direccioFacturacion = txtdireccionFacturacion.getText();
                String fechaEnvio = txtfechaEnvio.getText();
                String compania = cbcompania.getSelectedItem().toString();
                boolean finalizado = cbFinalizado.isSelected();
                envio.setIdEnvio(idEnvio);
                envio.setDireccionFacturacion(direccioFacturacion);
                envio.setFechaEnvio(fechaEnvio);
                envio.setCompania(compania);
                envio.setFinalizado(finalizado);

                this.limpiarCamposEnvio();
                this.listProducto();
                JOptionPane.showMessageDialog(this, "Editado Correctamente");
                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }

    }//GEN-LAST:event_btneditarEnvioActionPerformed

    private void btneliminarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarEnvioActionPerformed
        String idenvio = txtidEnvio.getText();
        boolean found = false;
        for (Envio envio : EnvioObjetoLista) {
            if (envio.getIdEnvio().equals(idenvio)) {
                this.EnvioObjetoLista.remove(envio);
                this.limpiarCamposEnvio();
                this.listProducto();
                JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btneliminarEnvioActionPerformed

    private void btncrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearClienteActionPerformed
        String cliente = txtidCliente.getText();
        String direccionCliente = txtdireccionCliente.getText();
        String telefono = txttelefonoCliente.getText();
        String email = txtemailCliente.getText();

        if (cliente.equals("") || direccionCliente.equals("") || telefono.equals("") || email.equals("")) {
            JOptionPane.showMessageDialog(this, "debes llenar todos los campos");
        } else {
            Cliente clienteUno = new Cliente(cliente, direccionCliente, telefono, email);
            clienteObjetoLista.add(clienteUno);
            this.listCliente();
            JOptionPane.showMessageDialog(this, "Registro Exitoso");
        }

    }

    private void listCliente() {

        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (Cliente cliente : clienteObjetoLista) {
            String data = cliente.getIdCliente() + " - " + cliente.getDireccion() + " - " + cliente.getTeleofono() + " - " + cliente.getEmail();
            model.add(index, data);
            index++;

            jList1.setModel(model);
        }


    }//GEN-LAST:event_btncrearClienteActionPerformed

    private void btnbuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarClienteActionPerformed
        String idCliente = txtidCliente.getText();
        boolean found = false;
        for (Cliente cliente : clienteObjetoLista) {
            if (cliente.getIdCliente().equals(idCliente)) {
                txtdireccionCliente.setText(cliente.getDireccion());
                txttelefonoCliente.setText(cliente.getTeleofono());
                txtemailCliente.setText(cliente.getEmail());

                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btnbuscarClienteActionPerformed

    private void btneditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarClienteActionPerformed
        String idCliente = txtidCliente.getText();
        boolean found = false;
        for (Cliente cliente : clienteObjetoLista) {
            if (cliente.getIdCliente().equals(idCliente)) {
                String Cliente = txtidCliente.getText();
                String direccionCliente = txtdireccionCliente.getText();
                String telefono = txttelefonoCliente.getText();
                String email = txtemailCliente.getText();
                cliente.setIdCliente(Cliente);
                cliente.setDireccion(direccionCliente);
                cliente.setTeleofono(telefono);
                cliente.setEmail(email);

                this.limpiarCamposCliente();
                this.listProducto();
                JOptionPane.showMessageDialog(this, "Editado Correctamente");
                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btneditarClienteActionPerformed

    private void btneliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarClienteActionPerformed
        String idCliente = txtidCliente.getText();
        boolean found = false;
        for (Cliente cliente : clienteObjetoLista) {
            if (cliente.getIdCliente().equals(idCliente)) {
                this.clienteObjetoLista.remove(cliente);
                this.limpiarCamposCliente();
                this.listProducto();
                JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                found = true;
                break;
            }

        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        }
    }//GEN-LAST:event_btneliminarClienteActionPerformed

    private void txtidProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidProductoActionPerformed
    private void limpiarCamposProducto() {
        txtnombreProducto.setText("");
        txtidProducto.setText("");
        txtprecioProducto.setText("");
        cbproveedor.setSelectedItem("");

    }

    private void limpiarCamposEnvio() {
        txtfechaEnvio.setText("");
        txtdireccionFacturacion.setText("");
        txtfechaEnvio.setText("");
        cbcompania.setSelectedIndex(0);
        cbFinalizado.setSelected(false);

    }

    private void limpiarCamposCliente() {
        txtidCliente.setText("");
        txtdireccionCliente.setText("");
        txttelefonoCliente.setText("");
        txtemailCliente.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btcrear;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnbuscarCliente;
    private javax.swing.JButton btnbuscarEnvio;
    private javax.swing.JButton btncrearCliente;
    private javax.swing.JButton btncrearEnvio;
    private javax.swing.JButton btneditarCliente;
    private javax.swing.JButton btneditarEnvio;
    private javax.swing.JButton btneliminarCliente;
    private javax.swing.JButton btneliminarEnvio;
    private javax.swing.JCheckBox cbFinalizado;
    private javax.swing.JComboBox<String> cbcompania;
    public javax.swing.JComboBox<String> cbproveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane listEnvio;
    private javax.swing.JTextField txtdireccionCliente;
    private javax.swing.JTextField txtdireccionFacturacion;
    private javax.swing.JTextField txtemailCliente;
    private javax.swing.JTextField txtfechaEnvio;
    private javax.swing.JTextField txtidCliente;
    private javax.swing.JTextField txtidEnvio;
    public javax.swing.JTextField txtidProducto;
    public javax.swing.JTextField txtnombreProducto;
    public javax.swing.JTextField txtprecioProducto;
    private javax.swing.JTextField txttelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
